"""add supplier and editable invoice data"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0937712dab68"
down_revision = "0002_audit_guard"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "suppliers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("name_key", sa.String(length=240), nullable=False),
        sa.Column("tax_number", sa.String(length=40), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "name_key", name="uq_supplier_company_name"),
    )
    op.create_index(op.f("ix_suppliers_company_id"), "suppliers", ["company_id"], unique=False)
    op.create_table(
        "invoice_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("invoice_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=22, scale=2), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=22, scale=2), nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=22, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=22, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=22, scale=2), nullable=False),
        sa.CheckConstraint(
            "net_amount >= 0 AND tax_amount >= 0 AND total_amount >= 0", name="ck_item_totals"
        ),
        sa.CheckConstraint(
            "quantity > 0 AND unit_price >= 0 AND discount_amount >= 0 AND tax_rate >= 0 AND tax_rate <= 100",
            name="ck_item_values",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_id", "position", name="uq_invoice_item_position"),
    )
    op.create_index(
        op.f("ix_invoice_items_invoice_id"), "invoice_items", ["invoice_id"], unique=False
    )
    op.add_column("invoices", sa.Column("supplier_id", sa.UUID(), nullable=True))
    op.add_column(
        "invoices",
        sa.Column("supplier_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("invoices", sa.Column("invoice_number", sa.String(length=100), nullable=True))
    op.add_column("invoices", sa.Column("invoice_date", sa.Date(), nullable=True))
    op.add_column("invoices", sa.Column("currency", sa.String(length=3), nullable=True))
    op.add_column(
        "invoices", sa.Column("subtotal", sa.Numeric(precision=22, scale=2), nullable=True)
    )
    op.add_column(
        "invoices", sa.Column("discount_total", sa.Numeric(precision=22, scale=2), nullable=True)
    )
    op.add_column(
        "invoices", sa.Column("tax_total", sa.Numeric(precision=22, scale=2), nullable=True)
    )
    op.add_column(
        "invoices", sa.Column("grand_total", sa.Numeric(precision=22, scale=2), nullable=True)
    )
    op.create_index(op.f("ix_invoices_supplier_id"), "invoices", ["supplier_id"], unique=False)
    op.create_foreign_key("fk_invoice_supplier", "invoices", "suppliers", ["supplier_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_invoice_supplier", "invoices", type_="foreignkey")
    op.drop_index(op.f("ix_invoices_supplier_id"), table_name="invoices")
    op.drop_column("invoices", "grand_total")
    op.drop_column("invoices", "tax_total")
    op.drop_column("invoices", "discount_total")
    op.drop_column("invoices", "subtotal")
    op.drop_column("invoices", "currency")
    op.drop_column("invoices", "invoice_date")
    op.drop_column("invoices", "invoice_number")
    op.drop_column("invoices", "supplier_snapshot")
    op.drop_column("invoices", "supplier_id")
    op.drop_index(op.f("ix_invoice_items_invoice_id"), table_name="invoice_items")
    op.drop_table("invoice_items")
    op.drop_index(op.f("ix_suppliers_company_id"), table_name="suppliers")
    op.drop_table("suppliers")
    # ### end Alembic commands ###
