import { StyleSheet } from "react-native";

export const colors = {
  ink: "#17332c",
  muted: "#64756f",
  primary: "#0b6b57",
  primaryDark: "#075244",
  primarySoft: "#e2f1ec",
  surface: "#ffffff",
  canvas: "#f4f7f5",
  line: "#dce5e1",
  warning: "#9a5c0a",
  warningSoft: "#fff3da",
  danger: "#a13838",
  dangerSoft: "#fdeaea",
  info: "#316275",
  infoSoft: "#e4f2f7",
};

export const commonStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.canvas },
  content: { padding: 18, paddingBottom: 36, gap: 14 },
  title: {
    color: colors.ink,
    fontSize: 25,
    lineHeight: 34,
    fontWeight: "900",
    textAlign: "right",
    writingDirection: "rtl",
  },
  subtitle: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 22,
    textAlign: "right",
    writingDirection: "rtl",
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 16,
  },
  label: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "800",
    textAlign: "right",
    writingDirection: "rtl",
  },
  input: {
    minHeight: 50,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#c9d6d1",
    backgroundColor: "#fff",
    paddingHorizontal: 14,
    color: colors.ink,
    fontSize: 16,
    textAlign: "right",
    writingDirection: "rtl",
  },
  primaryButton: {
    minHeight: 52,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: colors.primary,
    paddingHorizontal: 18,
  },
  primaryButtonText: { color: "#fff", fontSize: 16, fontWeight: "900" },
  errorBox: {
    borderRadius: 12,
    backgroundColor: colors.dangerSoft,
    borderWidth: 1,
    borderColor: "#f0c4c4",
    padding: 12,
  },
  errorText: {
    color: colors.danger,
    lineHeight: 21,
    textAlign: "right",
    writingDirection: "rtl",
  },
});
